image:
  file: .gitpod.dockerfile
tasks:
  - init: yarn install && yarn run build 
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data 
  - command: redis-server
  - command: yarn start
ports:
  - port: 4200
    onOpen: open-preview
  - port: 4500
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview
