version: "3"
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    logging:
      driver: "none"
  mongodb:
    image : mongo
    container_name: mongodb
    logging:
      driver: "none"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  api:
    depends_on:
      - mongodb
      - redis
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URL: ${MONGO_URL}
      REDIS_HOST: ${REDIS_HOST}
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  ws:
    depends_on:
      - mongodb
      - redis
    container_name: ws
    build:
      context: .
      dockerfile: Dockerfile.ws
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URL: ${MONGO_URL}
      REDIS_HOST: ${REDIS_HOST}
    ports:
      - "3002:3002"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  client:
    depends_on:
      - api
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
        - 4200:4200
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  widget:
    depends_on:
      - api
    container_name: widget
    build:
      context: .
      dockerfile: Dockerfile.widget
    ports:
        - 3500:3500
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  mongodb: ~
