[[redirects]]
  from = "/docs/:slug"
  to = "/:slug"
  status = 301
  force = false

[[redirects]]
  from = "/api"
  to = "https://novuapidocs.gatsbyjs.io/api/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
