# This is a basic workflow to help you get started with Actions

name: Test WEB

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Should deploy'
        required: false
        default: "true"
  pull_request:
    paths:
      - 'apps/web/**'
      - 'libs/shared/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test_web:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 80

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2.8

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true

      - uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint
          projects: "@notifire/web"

      - name: Start Local Stack
        env:
          DEFAULT_REGION: us-east-1
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCOUNT_ID: "000000000000"
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_EC2_METADATA_DISABLED: true
        working-directory: environment/test
        run: |
          docker-compose up -d
          sleep 5
          max_retry=30
          counter=0
          until $command
          do
             sleep 1
             [[ counter -eq $max_retry ]] && echo "Failed!" && exit 1
             aws --endpoint-url=http://localhost:4566 s3 ls
             echo "Trying again. Try #$counter"
             ((counter++))
          done
          aws --endpoint-url=http://localhost:4566 s3 mb s3://notifire-test

      # Runs a single command using the runners shell
      - name: Build
        run: CI='' pnpm build:web

      # Runs a single command using the runners shell
      - name: Start Client
        run: pnpm start:web &

      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          NODE_ENV: test
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          record: true
          working-directory: apps/web
          start: pnpm start:api
          wait-on: http://localhost:1336/v1/health-check
          browser: chrome
          headless: true
          install: false
