# This is a basic workflow to help you get started with Actions

name: Test API

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    paths:
      - 'package.json'
      - 'yarn.lock'
      - 'apps/api/**'
      - 'libs/dal/**'
      - 'libs/testing/**'
      - 'libs/shared/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test_api:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 80

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup kernel for react native, increase watchers
      run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
    - uses: actions/setup-node@v2
      with:
        node-version: '16.13.0'
    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.2.8

    - name: restore lerna
      uses: actions/cache@master
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

    # Runs a single command using the runners shell
    - name: Install project dependencies
      run: yarn install

    - name: Start Local Stack
      env:
        AWS_DEFAULT_REGION: us-east-1
        DEFAULT_REGION: us-east-1
        AWS_ACCOUNT_ID: "000000000000"
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
        AWS_EC2_METADATA_DISABLED: true
      working-directory: environment/test
      run: |
        docker-compose up -d
        sleep 10
        max_retry=30
        counter=0
        until $command
        do
          sleep 1
          [[ counter -eq $max_retry ]] && echo "Failed!" && exit 1
          aws --endpoint-url=http://localhost:4566 s3 ls
          echo "Trying again. Try #$counter"
          ((counter++))
        done
        docker-compose logs --tail="all"
        aws --endpoint-url=http://localhost:4566 s3 mb s3://notifire-test

      # Runs a single command using the runners shell
    - name: Bootstrap
      run: yarn run bootstrap

      # Runs a single command using the runners shell
    - name: Build API
      run: CI='' yarn run build:api

    # Runs a set of commands using the runners shell
    - name: Run a test
      run: |
        cd apps/api && yarn run test:e2e
        yarn run test

