name: Test providers
on:
  push:
    paths:
      - "providers/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: rm -rf build
      - run: pnpm install
      - run: pnpm build
      - name: Test
        run: pnpm test:providers
